server:
  port: 8085

spring:
  application:
    name: evaluation-service
  datasource:
    url: jdbc:mysql://localhost:3306/evaluation_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.199.130
      port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: campus-help-secret-key-for-jwt-token-2024
  expire: 604800000

logging:
  level:
    org.example: debug
