server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import:
      - nacos:db-config.yml
      - nacos:redis-config.yml
      - nacos:jwt-config.yml
      - nacos:feign-config.yml
      - nacos:mybatis-config.yml
      - nacos:order-service.yml
  cloud:
    compatibility-verifier:
      enabled: false
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/order_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      database: ${redis.database}
      timeout: ${redis.timeout}
      lettuce:
        pool:
          max-active: ${redis.lettuce.pool.max-active}
          max-idle: ${redis.lettuce.pool.max-idle}
          min-idle: ${redis.lettuce.pool.min-idle}