server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import:
      - nacos:db-config.yml
      - nacos:jwt-config.yml
      - nacos:mybatis-config.yml
      - nacos:user-service.yml
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/user_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1800000

management:
  endpoints:
    web:
      exposure:
        include: health,info
    endpoint:
      health:
        enabled: true
        show-details: when_authorized
      info:
        enabled: true